/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d436e768-73e8-4cb9-9532-9b486d2ff0d3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WsflwpFKV",
    "aws_user_pools_web_client_id": "3m0r0mo8o81rl87vvgcak5ep8q",
    "oauth": {},
    "aws_user_files_s3_bucket": "trabajodev496168c779bf42f3a73fd0dc20bdd153161317-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://knray2auxbe5nprztkbsgn2uca.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5qmkswdzijhnxmfppjkyvldsoi"
};


export default awsmobile;
